### ISSUE TITLE
Error in souffle-converter.py

### ISSUE THREAD

**Issue by Argc0** [ryzhyk/differential-datalog#216]
I was running this small test:
```
.decl AMethod(?simplename:symbol, ?descriptor:symbol, ?type:symbol, ?method:symbol)
.decl BMethod(?class:symbol, ?superclass:symbol)
.decl CMethod(?ref:symbol, ?interface:symbol)

AMethod(?simplename, ?descriptor, ?type, ?method) :-
  (BMethod(?type, ?supertype) ;
   CMethod(?type, ?supertype)),
  AMethod(?simplename, ?descriptor, ?supertype, ?method).
```
and I was trying to pass it via the souffle-converter.py
``` python souffle-converter.py example.dl example --logic-only```
but this error appeared :
```
Traceback (most recent call last):
  File "souffle-converter.py", line 1032, in <module>
    main()
  File "souffle-converter.py", line 1023, in main
    tree = parser.parse_file(files.inputName)
  File "/home/argc0/.local/lib/python2.7/site-packages/parglare/parser.py", line 133, in parse_file
    return self.parse(content, file_name=file_name, **kwargs)
  File "/home/argc0/.local/lib/python2.7/site-packages/parglare/parser.py", line 204, in parse
    raise error
parglare.exceptions.ParseError: Error at example.dl:6:10:"  (BMethod*(?type, ?s" => Expected: != or % or ) or * or + or , or - or / or : or < or <= or = or > or >= or AS or DOT or OR or ] or ^ or band or bor or bxor or land or lor or } but found <((()> or <NotComment((?type,)>
```

**Comment by mbudiu-vmw** [comment]
Currently ddlog has no "or" operator and the translation only accepts dnf rules. The only short term fix is to rewrite such rules by hand.

**Comment by mbudiu-vmw** [comment]
BTW: this is covered by #174
